[project]
name = "odoo-addons-oca-l10n-portugal"
version = "18.0.20250524.1"
dependencies = [
    "odoo-addon-l10n_pt_account_invoicexpress==18.0.*",
    "odoo-addon-l10n_pt_stock_invoicexpress==18.0.*",
    "odoo-addon-l10n_pt_vat==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
